name: golang-ci

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # リント処理
  go-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: golangci-lint-check
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_version: v1.55.0
          golangci_lint_flags: '-c .golangci.yml ./...'
          reporter: github-pr-review
          fail_on_error: true

  # ビルド処理
  build:
    runs-on: ubuntu-latest
    needs: go-lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Build
        run: go build ./...

  # テスト処理
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Test
        run: go test ./... -v
